# Generated by Django 5.0.5 on 2024-05-23 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_basket_amount_alter_basket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
